# Generated by Django 4.2.18 on 2025-01-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
