# Generated by Django 4.2.18 on 2025-02-16 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='editable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 7, 8, 34, 521733, tzinfo=datetime.timezone.utc)),
        ),
    ]
