# Generated by Django 4.2.18 on 2025-02-16 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_comment_editable_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='editable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 14, 12, 39, 134910, tzinfo=datetime.timezone.utc)),
        ),
    ]
