# Generated by Django 4.2.18 on 2025-02-16 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_request_has_new_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_replies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='editable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 17, 8, 49, 647295, tzinfo=datetime.timezone.utc)),
        ),
    ]
