# Generated by Django 4.2.18 on 2025-02-16 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_comment_has_replies_alter_comment_editable_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='editable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 18, 24, 29, 254931, tzinfo=datetime.timezone.utc)),
        ),
    ]
