# Generated by Django 4.2.18 on 2025-02-17 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_comment_delete_time_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='editable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 1, 7, 26, 455013, tzinfo=datetime.timezone.utc)),
        ),
    ]
