# Generated by Django 4.2.18 on 2025-02-17 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_userprofile_delete_time_userprofile_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='editable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 1, 45, 36, 812491, tzinfo=datetime.timezone.utc)),
        ),
    ]
