# Generated by Django 4.2.18 on 2025-02-17 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0028_comment_deleted_by_alter_comment_editable_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='editable_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 4, 17, 26, 637975, tzinfo=datetime.timezone.utc)),
        ),
    ]
